Update Changelog for v0.2.0-beta
hashicorp/terraform-helm pull request #24
Opened 2020-12-14 20:48 UTC by koikonom

2020-12-14 21:46 UTC, redeux reviewed
Looks like Chart.yaml needs a version bump

https://github.com/hashicorp/terraform-helm/blob/18777ff2bfc88dbad30dc3d266bb10bedc3086f2/Chart.yaml#L3

2021-01-05 22:45 UTC, aareet commented
A note to update the versions here once https://github.com/hashicorp/terraform-k8s/pull/86 is merged

2021-01-06 14:59 UTC, redeux commented on Chart.yaml
> +version: 0.2.0-beta
Needs the version bump here too.

2021-01-06 19:05 UTC, aareet approved these changes

2021-01-06 19:06 UTC, aareet requested changes

2021-01-06 19:07 UTC, koikonom commented on CHANGELOG.md
> +## 0.2.1 beta (Dec 14, 2020)
oops :)

2021-01-06 19:13 UTC, merged